### ISSUE TITLE
deploy a helloworld.war package to the same running tomcat server twice throw error

### ISSUE THREAD

**Issue by songkaiape** [adashen/vscode-tomcat#59] opened 2018-01-10 08:19 UTC
1.  create a dynamic web project by eclipse and generate a war package
2.  deploy the war package to tomcat server on VScode, it will success
3.  deploy the war package again to the same tomcat while it is running , error occured
![image](https://user-images.githubusercontent.com/4318793/34761947-d25787f8-f620-11e7-970a-ea8efc9bb610.png)

This issue doesn't reproduce on the spring boot sample project from [Here](https://github.com/spring-projects/spring-boot/tree/master/spring-boot-samples/spring-boot-sample-tomcat-jsp)
If we stop the tomcat server and redeploy the package. This issue doesn't reproduce either

**Comment by SummerSun** [comment] 2018-01-16 08:49
Whenever starting a tomcat server, we register a status bar command in vscode right bottom. The issue is caused by registering same command through different sessions.

The issue will be fixed by always using a same session to stop and restart a tomcat server via signal variable. Thus the status bar or command will be managed properly.

However, when a tomcat server is running, deploying war packages to it, or debugging war packages on it does not need server restart.

So after the fix, the behavior will be: 

- **restart** the tomcat server when switching between debug a war package and run war package on running tomcat server.

- **just re-deploy** war package to the server if it is running/debugging

**Closed** 2018-01-19 03:51 UTC
Labels: bug
